### PR TITLE
extended ID fix

### LINKED ISSUE #20: Throttle Position Sensor (TPS)
**Description**

**Definition of Done**
* Tested
* Code reviewed

### PR DESCRIPTION
**Pull request by WilliamLim781**
fixed the filter config for extended and changed the callback function to a flag

### Summary
fixed the filter id config and made the callback function into a flag based interrupt
### Checks
- [x] Tested
- [x] Stakeholder approval

### CODE REVIEW

File: Project/DAQ_System/Program/Src/app.cpp [hunk 1]
```diff
@@ -117,22 +116,265 @@ void cppMain() {
...
+	 	 	 1	   |  8  |     1 - 2      | 2 bytes				 3	  |  8  | 	     1       | 1 byte			     4    |  7  |	  1 - 2 	 | 2 bytes
+	  	  	  	   |	 |     3 - 4 	  | 2 bytes				      |     |        2		 | 1 byte					  |     |     3 - 4		 | 2 bytes
+	  	  	  	   |	 |     5 - 6 	  | 2 bytes				      |     |        3		 | 1 byte					  |     |     5 - 6		 | 2 bytes
+	  	  	  	   |	 |     7 - 8 	  | 2 bytes				      |     |        4		 | 1 byte					  |     |     	7	 	 | 1 bytes
+	  	 --------------------------------------------			      |     |        5		 | 1 byte			--------------------------------------------
+	  	 	 2	   |  6  |     1 - 2      | 2 bytes				      |     |        6		 | 1 byte				 5    |  8  | 	  1 - 2      | 2 bytes
+	  	  	  	   |	 |     3 - 4 	  | 2 bytes				      |     |        7		 | 1 byte					  |     |     3 - 4      | 2 bytes
+	  	  	  	   |	 |     5 - 6 	  | 2 bytes				      |     |        8		 | 1 byte					  |		|       5        | 1 byte
+	  	 --------------------------------------------		------------------------------------------					  |		|		6		 | 1 byte
+																														  |		|       7 		 | 1 byte
```
Comment (WilliamLim781) [inline Project/DAQ_System/Program/Src/app.cpp:183]: CAN data


The formatting be kinda off when I did the commit so I just have a snippet of the code comment here. I wanted to keep this comment here since I understand that the data type I created is kinda confusing so I wanted some visual on the code to help make sense of it

File: Project/DAQ_System/Program/Src/app.cpp [hunk 2]
```diff
@@ -117,22 +116,265 @@ void cppMain() {
...
+				printf("TPS = %.2f ", DecodeDataFrame[2]);
+				printf("Fuel Open Time = %.2f ", DecodeDataFrame[4]);
+				printf("Ignition Angle = %.2f \n", DecodeDataFrame[6]);
+				printf("\r");
+			}
+			if(CanID == 0x0CFFF548){
+				printf("\t\t 0x0CFFF548 \n");
+				printf("\r");
+				printf("Battery Volt = %.2f ", DecodeDataFrame[0]);
+				printf("Air Temp = %.2f ", DecodeDataFrame[2]);
```
Comment (WilliamLim781) [inline Project/DAQ_System/Program/Src/app.cpp:137]: can snippet

Here is what the serial monitor looked like. The data shown on the serial monitor seems to support my testing but obviously in person testing with the ECU is needed to fully validate if the CAN parsing is correct

File: Project/DAQ_System/Program/Src/app.cpp [hunk 3]
```diff
@@ -41,61 +37,64 @@ uint32_t canID;
...
+	canFilterSetup(3,CanIDList[2]);
+	canFilterSetup(4,CanIDList[3]);
+	canFilterSetup(5,CanIDList[4]);
+	canFilterSetup(6,CanIDList[5]);
+	canFilterSetup(7,CanIDList[6]);
+	canFilterSetup(8,CanIDList[7]);
+	canFilterSetup(9,CanIDList[8]);
+	canFilterSetup(10,CanIDList[9]);
+	canFilterSetup(11,CanIDList[10]);
+	canFilterSetup(12,CanIDList[11]);
```
Comment (WilliamLim781) [inline Project/DAQ_System/Program/Src/app.cpp:93]: I configured all the filters from the ECU for demonstration purposes. Obviously, we don't need all the filters here but I just wanted to show that the code could handle all the filters that  would be needed if we wanted to push the ECU's CAN bus to its limits

File: Project/DAQ_System/Program/Src/app.cpp [hunk 4]
```diff
@@ -117,22 +116,265 @@ void cppMain() {
...
 	}
 }
+
+
+void canFilterSetup(int FilterBankNum, uint32_t FilterExtID ){
+
+	// Filter initialization
+	CAN.FilterIdHigh = FilterExtID >> 13 ;
+	CAN.FilterIdLow = ((FilterExtID & 0x1FFF) <<3) | CAN_ID_EXT | CAN_RTR_DATA ;
+	CAN.FilterMaskIdHigh = 0xFFFF;
```
Comment (WilliamLim781) [inline Project/DAQ_System/Program/Src/app.cpp:154]: in the future i would like to actually configure a proper filter mask. It would be something like 0x00001100 Where the 1 represent hex digits that do get compared and the 0s are the hex digits that are don't cares

**Comment by WilliamLim781** [comment]
## Future considerations to the code
1.)The CAN bus code should really be put into another folder and turned into the library or something. The CAN code adds a lot of lines to the code and makes the overall app.cpp file cluttered and hard to read.

2.) Maybe CANIDList array could be turned into a #define. That may save space compared to using the array.

3.) For canFilterSetup() It might be a good idea to just automatically configure all filters or have two separate functions that select which id to filter and another function that just activates all filters.

4.) I also realized that I forgot to add the message flags properly =(. The flag is set in  the callback function but never reset so it kinda is true for the whole duration of the code.

5.) An overhaul on the data types of the canDecodeDataFrame() would also be nice. It works and it allows me to reduce the amount of lines needed to decode all the functions but I don't think it's very friendly to others reading the code. I think the approach is ok but the idea itself is kinda confusing or hard to convey via the comments.

**Comment by crsz20** [comment]
Great observation on defining your own generalized set of data types! I have some design ideas for improvement:

- You are defining custom data types and assigning numbers to them as an indicator. C++ [enums](https://www.programiz.com/cpp-programming/enumeration) allows you to do this while declaring a name for each. Suppose we name this enum `PE_Message`

```c++
enum PE_Message_Classification {
    FORMAT1,
    FORMAT2,
    ...
};
```
- We can define a lookup table to associate a CAN ID with one of the formats of the enum.
- Then, each enum format can have a corresponding struct.

```c++
struct Format4_Messagge {
   std::pair <uint8_t, uint8_t> field1; // 2 bytes
   std::pair <uint8_t, uint8_t> field2;
   std::pair <uint8_t, uint8_t> field3;
   std::pair <uint8_t, uint8_t field4; // Just 1 byte
}
```

- So, in practice, something along the lines of...

Pseudocode:
```
Decode() {
	PE_Message_Classification message_classification = lookup_table.val(canID)
	
	switch(message_classification)
           ...
           case(FORMAT4):  Format4_Messagge = Parse_Format_1(message_buffer, canID)
           ...

	switch(canID)
            ...
           case(0x0CFFF148): 
		RPM = Format4_Message.field1
		TPS = Format4_Message.field2
}

```

The constructor of each Message class can use parse 1 or 2 bytes at a time, accordingly.

**Comment by crsz20** [comment]
I think I have a more fleshed-out idea that's more reflective of the ECU's datasheet.

* The conversion algorithm can be a function: `int ParseBytePair(low_byte, high_byte)`.
* I will refer to your custom data type that you enumerated 1 through 5 as "Format1", "Format2", etc.
* By further examining the datasheet:
  * Frame "PE1" **is a** Format1 message.
  * Frame "PE2" **is a** Format4 message.
  * Notice the "is a" relationship — this is a potential use case for inheritance.
 
Consider each format as a structure:
```c++
struct Format1 {
  int num_of_fields = 4;
  int[num_of_fields] fields;

  // Constructor
  Format1(RxData[]) {
    // Parse RxData array using the BytePairParse function, storing the results in the fields[ ] array
  } 
};
```

This format will be re-used across different specific PE frames. So, let's define a class for the frame that inherits the format structure:
```c++
class PE1_Frame : public Format1 {
  // Constructor calls the constructor of Format1 to get access to fields
 PE1_Frame (RxData []) { ... }
  
  rpm_resolution_per_bit = 1;
  tps_resolution_per_bit = 0.1;

  GetRPM() { return fields[1] * rpm_resolution_per_bit; }
  GetTPS() { return fields[2] * tps_resolution_per_bit; }
}
```

* So, in practice, decoding upon receiving a new CAN message will look like this:
  * Identify CAN ID
  * Create the appropriate `PEx_Frame`, passing `RxData` to its constructor at initialization
  * Access final computed data using `PEx_Frame.GetRPM( )`
  * Pass the final computed data to the ECU class holding **all** data (we can then do input validation here)

Pseudocode:
```
Decode() {
  switch(canID) {
  case(0x0CFFF048):
    PE1_Frame frame(RxData[]);
    float rpm = frame.GetRPM();
    ...
  }
  case(...)
}

**Review by crsz20 — APPROVED** [review]
